### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by theskinnycoder** [coderaiser/minify#102]
Are there any resources out there that compares the default minification in build tools like Vite.js with this library? Also, Vite.js supports `esbuild` and `terser` as minification options, would they be better than this?

**Comment by coderaiser** [comment]
Do you see any benchmarks in repo? You can send PR with it.

**Comment by coderaiser** [comment]
https://github.com/putoutjs/minify/blob/master/README.md#how-its-compared-to-terser
