### ISSUE TITLE
Minify removes top-level js functions because it's "unused"

### ISSUE THREAD

**Issue by clrke** [coderaiser/minify#103]
I have a js file that I want to minify:

```js
function pluralize(noun) {
  return noun + "s";
}
```

Problem is, this function gets ignored by minify because it is "not being used" locally but I WILL be using this in another file.

Can we only remove unused variables inside these top-level functions?

**Comment by coderaiser** [comment]
Yes, create `.minify.json` file with:

```json
{
    "js": {
        "removeUnusedVariables": false
    }
}
```

**Comment by coderaiser** [comment]
Is it works for you?

**Comment by clrke** [comment]
@coderaiser Can we reopen? I want to keep `removeUnusedVariables` but only for those inside top-level functions.

**Comment by coderaiser** [comment]
This is not how [@putout/plugin-remove-unused-variables](https://github.com/coderaiser/putout/tree/v29.12.4/packages/plugin-remove-unused-variables#readme) works.

Why do you need to keep variables only inside top level functions? Could you please share code examples?
