### ISSUE TITLE
Class name minification should not be done by default.

### ISSUE THREAD

**Issue by Igor-Yavych** [coderaiser/minify#104]
Hello. 
9.x didn't minify class names, but 10.x does so we ran into an issue, where we have class, let's say `SuperbClass` and in another JS file we had `new SuperbClass()`.
Worked perfectly with 9.x, but in 10.x that `SuperbClass` became `a` and so reference from another file would fail.
I think there should be some option to explicitly enable class name minification

**Comment by coderaiser** [comment]
Just added ability to turn off `mangleClassNames`, create file `.minify.json` with:

```json
{
    "js": {
        "mangleClassNames": false
    }
}
```

Is it works for you?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
