### ISSUE TITLE
Invalid minification of computed method names

### ISSUE THREAD

**Issue by IJMacD** [coderaiser/minify#106]
test.js

```js
const a = {name:"key"};
const b = {
    [a.name] () { return 10; }
};
console.log(b.key());
```

Output:

    10

Minify:

    > npx minify@latest test.js

Minify Ouput:

```js
var a={name:"key"},b={a.name(){return 10}};console.log(b.key());
```

JS Error:

    Uncaught SyntaxError: Unexpected token '.'

Correct minified output:

```js
var a={name:"key"},b={[a.name](){return 10}};console.log(b.key());
```

**Comment by coderaiser** [comment]
Please re-install **Minify** and try again.
Is it works for you?

**Comment by IJMacD** [comment]
Yes, thank you. Working in latest version.

**Comment by IJMacD** [comment]
The issue seems to have been fixed in object literals but not in classes.

Here's another failing test case:

```js
const a = {name:"key"};
export class B {
    [a.name] () { return 10; }
};
console.log(new B().key());
```

**Comment by coderaiser** [comment]
Thank you! Just fixed, is it works for you?
