### ISSUE TITLE
Invalid minification of generators

### ISSUE THREAD

**Issue by IJMacD** [coderaiser/minify#107]
test.js:

```js
const a = {
    *gen () { yield 1; }
};
console.log([...a.gen()]);
```

Output:

    [1]

Minify:

    > npx minify@latest test.js

Minify Output:

```js
var a={gen(){yield 1}};console.log(a.gen());
```

JS Error:

    Uncaught SyntaxError: Unexpected number

Correct minified output:

```js
var a={*gen(){yield 1}};console.log([...a.gen()]);
```

(Note missing asterisk, missing array literal, and spread operator.)

**Comment by coderaiser** [comment]
Please re-install **Minify** and add `.minify.json` with:

```json
{
    "removeUselessSpread": false
}
```

Is it works for you?

**Comment by IJMacD** [comment]
Current output:

```js
var a={*gen(){yield 1}};console.log(a.gen());
```

The generator function is now being correctly minified.

However, the output after execution is still incorrect.

Expected:

    [1]

Actual:

    Object [Generator] {}

Adding the `.minify.json` file makes no difference.

**Comment by coderaiser** [comment]
My mistake, here is valid config:

```json
{
    "js": {
        "removeUselessSpread": false
    }
}
```

**Comment by IJMacD** [comment]
OK using this `.minify.json` produces correct output.

While `Array.from()` is a valid alternative the point here is not about coding style.

In its default configuration (with out `.minify.json`) **Minify** produces incorrect code. A minifier should never alter the runtime behaviour of code it transforms.

**Comment by coderaiser** [comment]
> While Array.from() is a valid alternative the point here is not about coding style.

The thing not just in code style, with syntax `[...fn()]` you can get a lot of things so [better to be concrete](https://github.com/coderaiser/putout/blob/master/packages/plugin-remove-useless-spread/README.md#array) so:
- other developers can understand code faster;
- tools can understand code better;
- redundant patterns can be dropped out when they don't needed;

About default behavior let's look how many people will trap on this, and if they will be a lot, we can of course make this default behavior in a future.

**Comment by IJMacD** [comment]
I'm sorry I strongly disagree with you on this point.

> The thing not just in code style

It is almost the definition of coding style. Two equivalent inputs produce identical results in un-minified code yet produce different results after minification.

```js
[...a].map((x,i) => `${i}: ${x}`)
```

or

```js
Array.from(a).map((x,i) => `${i}: ${x}`)
```

After minification:

```js
a.map((x,i) => `${i}: ${x}`);
```

JS Error:

    a.map is not a function

I think you misunderstand exactly what `a` could be. `Array` is only one possible option. `a` can be any iterable which is any object which implements the iterable protocol by defining [`Symbol.iterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) or any of the built in iterable types [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray), [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), and [Segments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment/Segments) or the [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) object or [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) of DOM elements.

Whether you agree with the programmer's choice to use `[...a]` or not, a minifier should **never** alter the runtime behaviour of the code

**Comment by IJMacD** [comment]
> The thing is minifier always alter runtime behavior, it changes const with vars, so there is no block scopes except functions, it changes if condition to logical expression and does other things.

Again, I think you misunderstand. The **syntax** will be different. That is expected and is the job of the minifier. However, the observable **behaviour** when executing the code should be _identical_.

> Why developer should ask all this questions each time he see this expression?

He doesn't need to. What exactly `a` is, is irrelevant. All the developer needs to know is that `a` is iterable, and this expression will turn it into an array.

It's strange to me that you think the `[...a,...b]` syntax is fine but `[...a]` isn't. The developers on your team either know what `[...X, ]` does or they do not.

But all of this really isn't important because you're breaking the biggest rule of a minifier. A minifier shot **not** be opinionated. It should not take valid code and produce invalid code. It should **not** change the runtime behaviour of code that is passed to it.

**Comment by IJMacD** [comment]
> I cannot reproduce this, after minification I have such results:
>      ```Array.from(a).map((x,i) => `${i}: ${x}`)```

Yes the second example produces that output, hence the two equivalent inputs produce two different outputs.

Ironically, you might consider adding a plugin to turn `Array.from(a)` into `[...a]` since they are equivalent and the length is 13 bytes vs 6 bytes.

**Comment by coderaiser** [comment]
> But all of this really isn't important because you're breaking the biggest rule of a minifier. A minifier shot not be opinionated. It should not take valid code and produce invalid code. It should not change the runtime behaviour of code that is passed to it.

There is no such a rule, but as I said, I'll add any options so you can produce stable code using **Minify**.

The options are added right now, and according to semantic versioning rule, changed options should be a breaking change, so at first I think we should get the full list of changed options and changed behavior before releasing a major version.
