### ISSUE TITLE
Object.keys turned into "keys"

### ISSUE THREAD

**Issue by patrick99e99** [coderaiser/minify#109]
I had the following line of code:
```
   var keys = Object.keys(LISTENERS.buttonClickHandlers);
```

and minify turned it into:
```
var B = keys(aX.buttonClickHandlers);
```

and the browser throws:
```
configuration.min.js:1 Uncaught ReferenceError: keys is not defined
```

The top of the file shows:
```
var{assign:a}=Object;
```

So it has destructured `assign`, but not `keys.`

**Comment by coderaiser** [comment]
Thank you, just fixed, please re-install **Minify**. Is it works for you?

**Comment by fritx** [comment]
@coderaiser really? such problem probably still exists. In my case
1. `'xxx' in history` turns into `'xxx' inhistory` causing SyntaxError
2. there is a `function _(){}` in the output causing conflict with lodash calls like `_.throttle is not a function`

My workaround was: `minify` css+html but `uglify` js files.

```sh
# Dockerfile
# ...
RUN npm i -g serve minify uglify-js

RUN cd blog && \
  uglifyjs vendor/blog.js > _.js && mv _.js vendor/blog.js && \
  minify vendor/blog.css > _.css && mv _.css vendor/blog.css && \
  minify index.html > _.html && mv _.html index.html
```

**Comment by coderaiser** [comment]
> 'xxx' in history turns into 'xxx' inhistory causing SyntaxError

Just fixed, about other cases please create new issue with code examples.
