### ISSUE TITLE
Can you also support mifinfy a markdown .md file? 

### ISSUE THREAD

**Issue by bestian** [coderaiser/minify#110]
type:  feature
scope: markdown
subject:  Can you also support mifinfy a markdown .md file? 

something like this:

```
function minifyMd(content) {
    // Remove extra whitespace
    let minified = content.replace(/\s+/g, ' ');
    // Remove unnecessary line breaks
    minified = minified.replace(/\n /g, '\n').replace(/ \n/g, '\n');
    return minified;
}
```

**Comment by coderaiser** [comment]
That’s a good idea for a PR :)

**Comment by coderaiser** [comment]
Actually as I see, what you want is not minifier for markdown, but rather linter, you can use 🐊[Putout](https://github.com/coderaiser/putout) to lint JavaScript inside your markdown files

**Comment by bestian** [comment]
No, the function is only an example of the parser

Not the input part.

Let me explain the feature I actually requested:


input: 

## Foo
Bar
Baz



Output:

## Foo Bar Baz

**Comment by coderaiser** [comment]
Code examples you provided has different meaning and they render differently:

## Foo
Bar Baz

## Foo Bar Baz

How it’s related to minification, and first provided example? To lint JavaScript inside markdown use 🐊**Putout**.
