### ISSUE TITLE
unable to compress js files containing Chinese

### ISSUE THREAD

**Issue by zhangmingxingAtGit** [coderaiser/minify#113]
When compressing a js file containing Chinese, the output file contains garbled characters :
```javascript
placeholder = `输入中文，在${engineName}上搜索`;
```
out : 
```javascript
placeholder=`杈撳叆涓枃锛屽湪${_b}涓婃悳绱;
```

**Comment by zhangmingxingAtGit** [comment]
When I use "npm run build" , the compression has no garbled characters. Run "minify a.js > b.js" directly in cmd, and the above garbled characters will appear

**Comment by coderaiser** [comment]
What version of node are you using?

**Comment by coderaiser** [comment]
I cannot reproduce this:

<img width="400" alt="image" src="https://github.com/coderaiser/minify/assets/1573141/dd82e828-98bf-4d23-905a-14d848ce7538">

Feel free to reopen when you have new details
