### ISSUE TITLE
Bug: transform code to unsafe code

### ISSUE THREAD

**Issue by yiqingpeng** [coderaiser/minify#114]
This lib will transform this code  `typeof(a) !== 'undefined'` to `(a)!==void 0`, when 'a' is not defined, will introduce JS error.

**Comment by ngdangtu-vn** [comment]
More case that kill me hard:

```js
// Before mangle
function everywhere() {}
function cool() { const list = []; for (const item of list) { everywhere() } }

// After mangle
function a() {}
function b() { const a = []; for (const b of a) { a() } }
```


Super realitic evident photo:

![image](https://github.com/coderaiser/minify/assets/68631458/e20f0b43-6a28-4934-bf6f-1be48985689f)

Good bye my fucking whole day :3

May I suggest to stop mangle top-level function name? Or just completely stop mangle every name? The `mangleClassNames` is not enough.

**Comment by ngdangtu-vn** [comment]
You should be extremely careful with mangling code man. Please refer this case if you wish to improve it: https://code.visualstudio.com/blogs/2023/07/20/mangling-vscode

**Comment by coderaiser** [comment]
> May I suggest to stop mangle top-level function name? Or just completely stop mangle every name? The mangleClassNames is not enough.

Just landed support of option `mangle`, now you can disable all mangle 🎉 . Please re-install **Minify**, is it works for you?

**Comment by ngdangtu-vn** [comment]
Is the new commit use the same version notation `10.5.2`? Should I clear cache and redownload it because I'm using Deno.

**Comment by coderaiser** [comment]
You need to have [`@putout/minify@2.4.0`](https://github.com/putoutjs/minify/releases/tag/v2.4.0) installed.

**Comment by ngdangtu-vn** [comment]
Ok, so that means refresh Deno cache: `deno run -r main.ts` 

It works nice, thanks.

**Comment by ngdangtu-vn** [comment]
I would like to reopen this issue as `mangle` option fails to work today. (It was really good yesterday though)

At first I suspect something wrong with Deno cache, so I look into its cache dir. But Deno get the right dep. However, to be safe, I remove a whole cache dir and re install. Still the mangling still be excuted even though I set it false.


```
import { minify } from "npm:minify@10.5.2";
const js_main = await minify(`${dir.src}/main.js`, {
  js: { mangle: false, mangleClassNames: false },
});
```

**Comment by coderaiser** [comment]
Could you please try to use `@putout/minify` directly?

**Comment by ngdangtu-vn** [comment]
```
import { minify as minifyjs } from "npm:@putout/minify@2.4.0";
```


```
error: Uncaught (in promise) SyntaxError: Invalid regular expression flag. (1:8)
    at e (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:199630)
    at Ql.raise (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:240060)
    at Ql.readRegexp (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:235589)
    at Ql.parseExprAtom (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:401006)
    at Ql.parseExprAtom (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:287740)
    at Ql.parseExprSubscripts (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:396113)
    at Ql.parseUpdate (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:395736)
    at Ql.parseMaybeUnary (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:395354)
    at Ql.parseMaybeUnaryOrPrivate (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:392237)
    at Ql.parseExprOps (file:///home/dangtu/.cache/deno/npm/registry.npmjs.org/@putout/minify/2.4.0/bundle/minify.min.js:1:392337)
```

I wonder if it because I upgrade deno :?

**Comment by coderaiser** [comment]
Could you please try node.js for this purpose :)?

**Comment by ngdangtu-vn** [comment]
I'll try it later

**Comment by ngdangtu-vn** [comment]
It doesn't work, and what make me curious the most now is why it worked before and then it wasn't.

```
import {minify} from 'minify';
// import {minify} from '@putout/minify'; // I tried to install it but it doesn't work, what did I do wrong?

console.log(minify);

const js_main = await minify(`main.js`, {
  js: { mangle: false, mangleClassNames: false },
})

console.log(js_main);
```

Did my code break it?

**Comment by coderaiser** [comment]
Have you tried to run in with nodejs?

**Comment by ngdangtu-vn** [comment]
> Have you tried to run in with nodejs?

Why would I lie to you?

![image](https://github.com/coderaiser/minify/assets/68631458/78470e7b-e03b-4303-aeb8-d1ad3892b5a2)

Does the minify use OS lib?

**Comment by coderaiser** [comment]
Here is commit with test:

https://github.com/putoutjs/minify/commit/f12c1e02f92eecab43cb4c546d72253a2cb70db9

Please provide me example of code you do not want to be mangled

**Comment by ngdangtu-vn** [comment]
I've send the file to your email, please confirm if you received it.

**Comment by coderaiser** [comment]
Just landed an update 🎉, please re-install **Minify**, is it works for you?

**Comment by ngdangtu-vn** [comment]
Thanks, for now it looks good. But let me confirm again tomorrow just to make sure that the bug is killed for good :D
