### ISSUE TITLE
BUG: After release v11.1.1, all HTML files are exported completelly in blank

### ISSUE THREAD

**Issue by TaylorHo** [coderaiser/minify#121]
I'm minimizing my HTML files using `npx minify --auto index.html > ./output/index.html`. It was working on version 11.0.1.

My minify.json file is the following:

```json
{
    "js": {
        "mangle": true,
        "mangleClassNames": true,
        "removeUnusedVariables": true,
        "removeConsole": false,
        "removeUselessSpread": true
    },
    "img": {
        "maxSize": 4096
    },
    "html": {
        "removeComments": true,
        "removeCommentsFromCDATA": true,
        "removeCDATASectionsFromCDATA": true,
        "collapseWhitespace": true,
        "collapseBooleanAttributes": true,
        "removeAttributeQuotes": false,
        "removeRedundantAttributes": true,
        "useShortDoctype": true,
        "removeEmptyAttributes": true,
        "removeEmptyElements": false,
        "removeOptionalTags": false,
        "removeScriptTypeAttributes": false,
        "removeStyleLinkTypeAttributes": true,
        "minifyJS": true,
        "minifyCSS": true
    },
    "css": {
        "compatibility": "*"
    }
}
```

After upgrading to 11.1.1, HTML files are exported completely in blank, CSS and JS files keept the same.

**Comment by coderaiser** [comment]
I cannot reproduce this:
![image](https://github.com/coderaiser/minify/assets/1573141/c6bf931b-6442-4320-b9df-321311c58208)

Please re-install **Minify** and try again, is it works for you?

**Comment by TaylorHo** [comment]
Okay, I've tested a little more:

Using it like `cat index.html | npx minify --html > teste.html` works.

But using it like below doesn't work:

- `npx minify --html index.html`
- `npx minify --html index.html > test.html`

I'm using a mac with ARM processor, but it also haven't worked on Github Actions.

And booth, the v11.0.1 and v11.1.1 (the booth I've tested) aren't working.

**Comment by coderaiser** [comment]
> cat index.html | npx minify --html > teste.html

this is documented and correct way, to read stream and understand what type of file is piped. If you pass file as argument to **Minify** flag `—-html` not needed, type determined by file extension.
