### ISSUE TITLE
Why const a; is replaced by var a; ?

### ISSUE THREAD

**Issue by franck-paul** [coderaiser/minify#123]
I use the 9.2.0 version of this tool since years and I just updated it to the 11.2.0 release and I discover that all my const/let variable declaration have been replaced by var which, imho, may have side-effects as soon as more than one minified scrips are loaded in a single page.

Could you explain me why you do this?

**Comment by franck-paul** [comment]
Forget this issue, it all about scope.

**Comment by coderaiser** [comment]
`var` has one byte less then `const` but yes `let` use also good, and even better then `var`.

You can switch to [old behaviour](https://github.com/coderaiser/minify#js).
