### ISSUE TITLE
Minify being too aggressive

### ISSUE THREAD

**Issue by dehli** [coderaiser/minify#124]
Hello, thanks for your work on this library! Recently ran into an issue and I figured out it was due to `minify` removing more parenthesis than it should.

The following JavaScript code creates a JS script and appends it to the the document (we had some similar code for analytics).

```js
url="https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js";
(p = document.createElement("script")).type = "application/javascript",p.src = url;
(r=document.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);
```

when calling `npx minify` it returns the following (new lines inserted for formatting):

```js
url='https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js';
p=document.createElement('script').type='application/javascript',p.src=url;
r=document.getElementsByTagName('script')[0].parentNode.insertBefore(p,r);
```

The bug is that `p` is no longer the created script but it's now the string "application/javascript" since the parenthesis were removed. Similarly `r` is assigned the wrong value. This issue was introduced in 11.2.1.

**Comment by coderaiser** [comment]
Thank you! Just fixed, please re-install **Minify**.
Is it works for you?

**Comment by dehli** [comment]
Thank you! I uninstalled and reinstalled and `minify` is now behaving as I'd expect. Thanks for the quick fix!
