### ISSUE TITLE
Minifying breaks some JS code

### ISSUE THREAD

**Issue by Akrobate** [coderaiser/minify#125]
Hello noticed some strange choices made by the the minifier

My original function
![image](https://github.com/user-attachments/assets/f6f066fc-aa09-46a5-a4e9-f51248ea8115)

Has been minified to this (I reindented it) :
![image](https://github.com/user-attachments/assets/c80c86f1-1aa7-4435-97ed-95a8568ea6ac)

It is not the same thing =)

**Comment by coderaiser** [comment]
One of solutions would be to use [xor swap](https://en.wikipedia.org/wiki/XOR_swap_algorithm).
But I agree with you, this should be kept as is:

```js
const tmp = a[index];
a[index] = a[index-1];
a[index-1] = tmp;
```

**Comment by coderaiser** [comment]
Just fixed, please re-install **Minify**

**Comment by Akrobate** [comment]
Great! Just tested it! Works as expected!
Much better this way ;-)

Thank you =)
