### ISSUE TITLE
Minified js with apostrophe in a "" string is broken

### ISSUE THREAD

**Issue by fuhrmanator** [coderaiser/minify#127]
With the latest (11.4.1) I minified this mwe.js file:

```js
throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
``` 

and I get 

```js
throw Error('Can't start parsing from rule \"'+options.startRule+'\".');
```

which is invalid javascript. I hope my example is useful - it happened on a much bigger project, but you get the idea.

**Comment by fuhrmanator** [comment]
Version 10.3.0 seems to work, and produces

```js
throw Error("Can't start parsing from rule \""+options.startRule+"\".");
```

I think it broke shortly after? Hope this helps.

**Comment by fuhrmanator** [comment]
Sadly, it looks like 10.3.0 breaks other things (my minified pegjs parser doesn't pass the jest tests).

**Comment by coderaiser** [comment]
Could you please provide code example and stack trace

**Comment by fuhrmanator** [comment]
The original message has a sample input and (bad) output. It's not crashing (no stack trace), but the minified result is not valid JavaScript.

**Comment by coderaiser** [comment]
Just landed ability to override quotes type, use [options](https://github.com/coderaiser/minify/blob/master/README.md#options) in `.minify.json`. Is it works for you?

**Comment by fuhrmanator** [comment]
It seems strange to have to set a config to make it generate valid .js. Anyway, I removed minify from my project, because it's not really necessary and adds a dependency to my build/release.

**Comment by coderaiser** [comment]
You can suggest a way to detect type of quotes you are using from Babel AST.
