### ISSUE TITLE
Minifying omits relevant line, breaks JS script

### ISSUE THREAD

**Issue by leherkom** [coderaiser/minify#132]
I wrote a simple JS script that finds a specific date in the next month and returns it as a Date object. While debugging, I noticed that minifying the script breaks the year rollover.

The original piece of the code looks like this:
```js
const now = new Date();
now.setDate(1);
if (now.getMonth() < 11) {
  // increase month by 1 if it is not currently December
  now.setMonth(now.getMonth() + 1);
} else {
  // else, consider year rollover and go to next January
  now.setMonth(0);
  now.setFullYear(now.getFullYear() + 1);
}
```

This is minified to (slightly reformatted for readability):
```js
var B=new Date();
B.setDate(1);
B.getMonth() < 11 ? B.setMonth(B.getMonth()+1) : B.setMonth(0);
```

The line that would increase the year number when doing a year rollover seems to be deemed unnecessary and is removed. This happened while using the CLI with no additional options in a global install from npm (`minify index.js > index.min.js`).

**Comment by coderaiser** [comment]
Just fixed, please re-install **Minify**. Is it works for you now?

**Comment by leherkom** [comment]
Yes, can confirm it works now. Thank you!
