### ISSUE TITLE
Sync method

### ISSUE THREAD

**Issue by IonicaBizau** [coderaiser/minify#28]
Is it possible to have a sync version?

```js
var minified = minifySync("foo.js");
```

**Comment by coderaiser** [comment]
Actually main purpose of `minify` is async work, as node-way. But with [iojs](https://iojs.org) or `--harmony` flag of `node v0.11` and [ruff](https://github.com/coderaiser/ruff) with help of [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function* "generators") you could use minify like this:
```js
var ruff    = require('ruff'),
    minify  = require('minify');

ruff(function*(thunk) {
    var mini        = thunk(minify, 'lib/ruff.js'),
        result      = yield mini;

    console.log(result)
}).on('error', function(error) {
    console.log(error);
});
```
Why you need sync version?

**Comment by IonicaBizau** [comment]
> Why you need sync version?

For some mad science things. :smile: But actually with the [`deasync`](https://www.npmjs.com/package/deasync) module any async function can be converted in sync, which what I need.

Currently I have this code that probably works, I didn't test it:
```js
function _de(async, args) {
    var _done = false
      , _args = null
      ;

    args = args || [];

    async.apply(this, args.concat([function () {
        _done = true;
        _args = arguments;
    }]));

    while(_done === false) {
        Deasync.runLoopOnce();
    }

    if (_args[0]) {
        throw _args[0];
    }

    return _args[1];
}

function minifySync(path) {
    return _de(minify, [path]);
}
```
