### ISSUE TITLE
Support reading from STDIN instead of a file

### ISSUE THREAD

**Issue by mcandre** [coderaiser/minify#29]
As a Unix user, I want minify to treat the fielname `-` to mean read from STDIN rather than a file, so that I can pipe data directly to minify without having to save it in a file.

**Comment by coderaiser** [comment]
But you could do this. As `Command Line` part of [minify site](http://coderaiser.github.io/minify/) says.
You could do such things this way:

```sh
cat client.js | minify -js
cat *.css | minify -css
```
Anyway you should specify what type of file you going to minify.

**Comment by mcandre** [comment]
Thanks for pointing that out, I should have read the docs better.
