### ISSUE TITLE
fix(output) css file without rules results in '' == true

### ISSUE THREAD

**Issue by mwitjes** [coderaiser/minify#32]
Using the command line on windows, minifying a css file without any rules (only comments) results in '' == true. I assume the file is interpreted as a javascript file. If so, is there a way to force the type of minification on windows using command line?

To reproduce:
* file test.css containing: /* dummy comment */
* command line: minify test.css
* output: '' == true

**Comment by coderaiser** [comment]
Just tried the same, could not reproduce.
```sh
minify test.css #  /* dummy comment */
# just empty string
```

Try to install last version of `minify`. 
About flags, there is such, try this on windows:
```sh
type 1.css| minify -css
```

**Comment by mwitjes** [comment]
Thank you for your quick response.

I think I have the latest version via npm:
├─┬ minify@1.4.22
│ ├─┬ clean-css@3.4.6
│ │ ├─┬ commander@2.8.1
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.0

I am still getting the error. See the screenshot below
![afbeelding 183](https://cloud.githubusercontent.com/assets/15261109/10699437/101b8f3c-79b7-11e5-9481-a95f8ac55c70.png)

When entering type 1.css| minify -css on the command prompt I get an error "The system cannot find the file specified"

**Comment by coderaiser** [comment]
your file named `test.css` so you should try
```sh
type test.css|minify -css
```

**Comment by coderaiser** [comment]
Here is my log, try this:
```sh
D:\Temp\31337>echo "/* hello world */" > test.css
D:\Temp\31337>minify test.css
""
D:\Temp\31337>type test.css|minify -css
""
```

**Comment by mwitjes** [comment]
Thank you. I don't think the file should contain double quotes. Take a look at my log. It still outputs '' == true without the flag. 

![image](https://cloud.githubusercontent.com/assets/15261109/10710218/1286c032-7a4f-11e5-9138-7d33a5eebe4d.png)

But with the flag it appears to work. Thank you very much.
