### ISSUE TITLE
Available as a static library file?

### ISSUE THREAD

**Issue by sahildua2305** [coderaiser/minify#34]
I want to use this in my project where node module can't be used. I have an option of including a static library file and get things done using that file.

Any way I can use this library as a static file to simply include in my project?

**Comment by coderaiser** [comment]
[Browserify](http://browserify.org/) can help you with this.

**Comment by sahildua2305** [comment]
Thanks for responding @coderaiser 

I found an [alternative](https://cdnjs.com/libraries/prettydiff) which is available as a static library (using browserify wasn't a good option considering the infrastructure).
