### ISSUE TITLE
CSS comment block is not being removed

### ISSUE THREAD

**Issue by davidenco** [coderaiser/minify#35]
I am minifying several CSS files into one. Some files have /** comment blocks **/ and are not being removed as part of the minification. Using Minify v2.0.10.

**Comment by coderaiser** [comment]
I can't reproduce:
```sh
coderaiser@cloudcmd:~$ minify -v
v2.0.10
coderaiser@cloudcmd:~$ echo "{/* comments */ color: red}" | minify --css
{color:red}
```
Could you give me some example?

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
