### ISSUE TITLE
minify fails on es6 template literals (`whatever`) 

### ISSUE THREAD

**Issue by chrisGoad** [coderaiser/minify#36]
Emits an error with message:  Unexpected error character `

**Comment by coderaiser** [comment]
The thing is `minify` uses [uglify](https://github.com/mishoo/UglifyJS2) for js minification. 
Unfortunately `uglify` [doesn't support minification of es6 yes](https://github.com/mishoo/UglifyJS2/issues/448) and I do not know any uglifiers with similar functionality and es-support.

Anyway you can use [babel](https://babeljs.io/) for this purpose. This is how:

```sh
coderaiser@cloudcmd:~$ cat > hello.js
const hello = 'world';
console.log(`${hello}`);
if (false) { console.log(hello);}
^C

coderaiser@cloudcmd:~$ babel --preset es2015 hello.js | minify --js
"use strict";var hello="world";console.log(""+hello);
```

Is it works for you?

**Comment by Martii** [comment]
Hmm this was working from OUJS perspective a little while back. Is this repo using the harmony branch?

**Comment by coderaiser** [comment]
What is `OUJS`? This repo uses [uglify from npm](https://github.com/coderaiser/minify/blob/master/package.json#L40).

**Comment by chrisGoad** [comment]
Thank you for your response.  My use of template literals was very minimal,
and the easiest thing for me to do has been to dispense with them.  Do
think uglify might evolve towards complete  es6 support? Maybe I'll monitor
that.

--Chris

**Comment by coderaiser** [comment]
I think it definitely will. It event has [harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony) and I think they will merge it to master someday.

**Comment by Martii** [comment]
@coderaiser 

[harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony) and of course you may already know [the issue thread](https://github.com/mishoo/UglifyJS2/issues/448).

> This repo uses uglify from npm.

That would probably be why your template string literals are failing is because you are using the ES5 master which is published to npmjs.com and not the harmony branch.

**Comment by coderaiser** [comment]
@martii I don't think that using code under active development that has no version is a good idea. I think they will merge some day (I hope it will be soon :)).

**Comment by Martii** [comment]
@coderaiser 

> I think they will merge some day (I hope it will be soon :)).

Us too but our project/repo/production is currently listing it as experimental and there is strong interest. :)
