### ISSUE TITLE
stream

### ISSUE THREAD

**Issue by thorinisme** [coderaiser/minify#38]
can we pipe stream to minify ?

**Comment by coderaiser** [comment]
Yes, [you can](https://github.com/coderaiser/minify/issues/29), with:

```sh
cat *.css | minify -css
```

**Comment by thorinisme** [comment]
I am looking for something like

```js
myFileStream.pipe(minify).pipe(storeInCache)
```

My goal is the cache manager automaticaly store minified files in ram if environment is production.

**Comment by coderaiser** [comment]
Unfortunately `uglify` and `html-minifier` which are used in `minify` doesn't support streams. They load file completely and then process it.
