### ISSUE TITLE
No way to pass arguments to uglify-js

### ISSUE THREAD

**Issue by matutter** [coderaiser/minify#39]
I want to pass arguments to uglify and I can't find a way to do it

```javascript
var uglify_opts = { compress: { dead_code: true } }
minify('file.js', uglify_opts, (e, data) => {
    //... do stuff
}) 
```

And I'm looking through the source, i don't think they even get passed?

**Comment by coderaiser** [comment]
Actually they [get passed](https://github.com/coderaiser/minify/blob/master/lib/js.js#L31). Feel free  to make pull request with ability of passing arguments because there is no way to do it right now :).

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
