### ISSUE TITLE
Cannot find module '..'

### ISSUE THREAD

**Issue by davidenco** [coderaiser/minify#43]
Using the following CSS:

@font-face {
    font-family: 'Open Sans';
    font-weight: normal;
    font-style: normal;
    src: local('Open Sans'),
    local('Open-Sans-regular'),
    url('../fonts/OpenSans2/Regular/Open-Sans-regular.woff2') format('woff2'),
    url('../fonts/OpenSans2/Regular/Open-Sans-regular.woff') format('woff');
}

From the current working directory, I can access the paths above as they are (including the ".."). However when trying to minify the CSS file, the output is:

Cannot find module '..'

I am using minify v2.1.6, npm v5.0.3 and nodejs v6.11.0.

**Comment by coderaiser** [comment]
Thank you, fixed with fd32fa7, landed in [v2.1.7](https://github.com/coderaiser/minify/releases/tag/v2.1.7).
