### ISSUE TITLE
How to use minify in webpages ?

### ISSUE THREAD

**Issue by darkworks** [coderaiser/minify#44]
Hi i want to use minify on client side , so any idea how to do it , i search i found webpacks , browerify , so can you guide me to make package of it so that it can be used on client side

thanks

**Comment by coderaiser** [comment]
To make `minify` work on client side should be made some changes: [work with file system](https://github.com/coderaiser/minify/blob/master/lib/minify.js#L73) and [tomas]() should be moved out to `bin`.

Or something like [filer](https://github.com/filerjs/filer) should be added.
Anyways it is a great idea to make `minify` able to work on the client side :).

**Comment by darkworks** [comment]
ok am not nodejs developer so cant help , so when you have any update on client side version let us know 

thanks :)

**Comment by coderaiser** [comment]
Closed due to long time of inactivity
