### ISSUE TITLE
Enhancement: Select the minimum length format for strings

### ISSUE THREAD

**Issue by mcandre** [coderaiser/minify#45]
To further shrink JS content, we can select string literal formats tailored to reduce the number of escape characters involved, for each individual string constant. E.g., `'"'` is preferable to `"\""`, and `"'"` is preferable to `'\''`.

* [ ] For each string constant, compare how the constant would be quote-escaped in double- vs. single-quoted formatted literals.
* [ ] Select the minimal length format for that particular string constant and emit to output.
* [ ] Disregard backticked, interpolated strings from this optimization.

**Comment by coderaiser** [comment]
It is an interesting idea, here is file that needs to be changed for this purpose: [js](https://github.com/coderaiser/minify/blob/0f6ea587f3ea8cfddffef7870c028a95fcc0afdd/lib/js.js). Are you up to contribute :)?

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
