### ISSUE TITLE
No output on Windows

### ISSUE THREAD

**Issue by nero120** [coderaiser/minify#47]
Using the latest version (3.0.4) installed globally, the output file is always blank regardless of whether I'm minifying js or css files. I'm using this on the command line, i.e.:

```
minify scripts.js > script.min.js
```

**Comment by coderaiser** [comment]
Thank you :), fixed with 2d6988e. Landed in [v3.0.5](https://github.com/coderaiser/minify/releases/tag/v3.0.5).

**Comment by nero120** [comment]
Fast work dude!
