### ISSUE TITLE
example

### ISSUE THREAD

**Issue by cekvenich** [coderaiser/minify#49]
Is there an example of min.js it creates?

**Comment by coderaiser** [comment]
[Here](https://github.com/coderaiser/minify/blob/master/README.md#cli) you can find it.

**Comment by cekvenich** [comment]
That shows how to use it. Not an example of an output.

**Comment by coderaiser** [comment]
`Minify` doesn’t create a file. You should [redirect output](https://en.wikipedia.org/wiki/Redirection_(computing)) to a `min.js` file by yourself.
