### ISSUE TITLE
Save direct to file

### ISSUE THREAD

**Issue by metalfox6383** [coderaiser/minify#51]
Hi:

Thanks for the package. It's great.

Can you add a third parameter for save the content into a file?

By example: 
`minify 'file.js' 'file.min.js'`

That to create a file 'file.min.js' with the content minified.

Thanks.

**Comment by coderaiser** [comment]
Why can't you just use?

```sh
minify file.js > file.min.js
```

This will minify all js files and output minified version of it.

```sh
minify file1.js file2.js 
```

So what you are asking about is a major change. Is it worse it?

**Comment by metalfox6383** [comment]
Oh! Thanks! I did not know the operator ">". This operator is enough for me. Thanks again! God bless you.
