### ISSUE TITLE
^D in readme

### ISSUE THREAD

**Issue by DanielRuf** [coderaiser/minify#53]
Why is there a `^D` in the readme?

**Comment by coderaiser** [comment]
`^D` is for quit from `cat > 1.js` command :)

**Comment by DanielRuf** [comment]
Ok but isn't this very system specific (Linux, macOS)? Generally the steps should be "create file x", "run command y".

This looks more like a Linux based readme with the shell sign, the exit command and so on.
This might be confusing to others too.

**Comment by coderaiser** [comment]
This is a great idea for a Pull Request with improvements :)

**Comment by coderaiser** [comment]
Fixed with https://github.com/coderaiser/minify/pull/54 :)
