### ISSUE TITLE
Use html-minifier-terser instead of html-minifier

### ISSUE THREAD

**Issue by Tsuk1ko** [coderaiser/minify#59]
Could you consider using [terser/html-minifier-terser](https://github.com/terser/html-minifier-terser) instead of kangax/html-minifier?

They are almost the same, but kangax/html-minifier dosn't support es6 when minify scripts in html. (see [kangax/html-minifier#1076](https://github.com/kangax/html-minifier/issues/1076))

**Comment by coderaiser** [comment]
Thank you :), landed to [v6.0.0](https://github.com/coderaiser/minify/releases/tag/v6.0.0) 🎉
