### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Ghost---Shadow** [coderaiser/minify#65]
I tried googling it it seems that this package is not available in some version of node 12. However I am using node 13.

https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly

What is the recommended version of nodejs where this works?

```
➜  word-highlighter git:(master) ✗ npx minify ./build/build.js > ./build/build.min.js
Cannot find module 'fs/promises'
Require stack:
- /mnt/c/Users/windows/Desktop/word-highlighter/node_modules/minify/lib/minify.js
- /mnt/c/Users/windows/Desktop/word-highlighter/node_modules/minify/bin/minify.js
➜  word-highlighter git:(master) ✗ which node
/home/user/.nvm/versions/node/v13.14.0/bin/node
```

**Comment by coderaiser** [comment]
Node.js < v14 is not supported since [minify v7.0.0](https://github.com/coderaiser/minify/releases/tag/v7.0.0)
