### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by flashsites-flowhub** [coderaiser/minify#66]
When I make an fresh installation with minify and do execute it, I get this error:

Error: Cannot find module 'fs/promises'
Require stack:
- C:\Projects\.\.\.\node_modules\minify\lib\minify.js
- C:\Projects\.\.\.\app\Helpers\File.js
- C:\Projects\.\.\.\node_modules\require-stack\src\index.js
- C:\Projects\...\.\.\node_modules\require-stack\index.js
- C:\Projects\...\...\...\node_modules\@adonisjs\fold\src\Ioc\index.js
- C:\Projects\,,,\...\...\node_modules\@adonisjs\fold\index.js
- C:\Projects\...\...\..\server.js

**Comment by coderaiser** [comment]
Could you please tell me what version of `node.js` do you using?

**Comment by coderaiser** [comment]
Looks like the problem in node.js version, consider upgrading to v14.
