### ISSUE TITLE
Usage with rollup ?

### ISSUE THREAD

**Issue by kiuKisas** [coderaiser/minify#71]
Hi !
I was wondering if there is an easy integration with rollup ?
Thank's !

**Comment by coderaiser** [comment]
Hi, there is no such integration. But that’s a good idea for PR. How do you think what could be first step?

**Comment by kiuKisas** [comment]
I have no clue for now, I let you know if I take time to dig into it.
A good start, I guess, would be to have a look on how `terser` implement a rollup plugin: https://www.npmjs.com/package/rollup-plugin-terser

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
