### ISSUE TITLE
Convert to ESM

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/minify#74]
Would be amazing to convert `minify` to `ESM`. [@putout/plugin-convert-commonjs-to-esm](https://github.com/coderaiser/putout/tree/master/packages/plugin-convert-commonjs-to-esm) can help with it.

**Comment by Zapotoczny-Rafal** [comment]
I would like to contribute to this issue, but i don't promise i'll do it correctly the first time

**Comment by Zapotoczny-Rafal** [comment]
Hi @coderaiser, I'm done converting this, but there is one problem with the for loop

`for (const name of ['js', 'html', 'css', 'img']) {
    minify[name] = require(DIR + name);`

I have not found information on how to convert it to the esm module, so I changed these four files to commonjs with .cjs extension. Can it be like that?

**Comment by coderaiser** [comment]
You can use [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) for this purpose

**Comment by coderaiser** [comment]
✅
