### ISSUE TITLE
Apply try-catch in lib/libOptions

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/minify#77]
Apply [`try-catch`](https://github.com/coderaiser/try-catch) and change signature of [`lib/options.js`](https://github.com/coderaiser/minify/blob/v7.1.0/lib/options.js) so it was the same as `try-catch` has: a tuple (an array) with two elements: `[error, options]`.

- *Do not forget to update [`bin/minify.js`](https://github.com/coderaiser/minify/blob/v7.1.0/bin/minify.js).*
- *Do not forget to update [`test/libOptions.js`](https://github.com/coderaiser/minify/blob/v7.1.0/test/libOptions.js).*

**Comment by theyup12** [comment]
Can I work on it, But this is my first time contributing

**Comment by coderaiser** [comment]
@theyup12 sure :)

**Comment by coderaiser** [comment]
Landed in [v7.2.0](https://github.com/coderaiser/minify/releases/tag/v7.2.0) 🎉
