### ISSUE TITLE
Force minify file with unsupported extension

### ISSUE THREAD

**Issue by williamd5** [coderaiser/minify#90]
I was surprised to find out that minify [refuses to minify](https://github.com/coderaiser/minify/blob/29b2da7aef3ed8af26b33b90da756e337c412df3/lib/minify.js#L43) .ejs files (which essentially are HTML) and I assume this is determined by the file extension, as the file Content-Type is text/html.

It would be particularly handy to be able to force minify a file, i.e. by providing the type with an additional argument. For instance

```sh
minify index.ejs --type html
minify file --type js
```
etc.

Do let me know if I shall make a PR.

**Comment by coderaiser** [comment]
This is amazing idea for a Pull Request :)! `minify` should definitely support `ejs`, and other unknown files according to passed type.

**Comment by williamd5** [comment]
I see that in `help` the arguments `--html`, `--css` and `--js` are already supported. Should I use these?

**Comment by coderaiser** [comment]
> I see that in help the arguments --html, --css and --js are already supported. Should I use these?
Yes, it runs minifying according to supported types

**Comment by coderaiser** [comment]
Use:

```sh
cat index.ejs | minify --html
```

Or since [v10.1.0](https://github.com/coderaiser/minify/releases/tag/v10.1.0):

```sh
cat index.ejs | minify --auto
```
