### ISSUE TITLE
Can't use `require` in blank node project

### ISSUE THREAD

**Issue by exactchange** [coderaiser/minify#93]
Does it only work with `import`?

![Screenshot from 2022-06-19 13-37-53](https://user-images.githubusercontent.com/45407493/174499524-8c511875-a8a3-4b71-a173-36b15ed7cf72.png)

**Comment by coderaiser** [comment]
Yes, only import supported.

**Comment by exactchange** [comment]
> Yes, only import supported.

Because this library is just combining other libraries, would make more sense if you made it work with the primary use case: Minifying files in a node environment when deploying, etc.

**Comment by coderaiser** [comment]
Node environment supports imports since node v12.

Why do you need `require`?

**Comment by bennyschmidt** [comment]
> Node environment supports imports since node v12.

Incorrect

> Why do you need `require`?

The same reason millions of other projects do, JavaScript isn't just React and Webpack.

Don't worry about it. The 4 other libraries you put together to make this one already have Node support so I can just use them directly

**Comment by coderaiser** [comment]
> Incorrect

https://nodejs.org/dist./v12.12.0/docs/api/esm.html#esm_code_import_code_statements

**Comment by bennyschmidt** [comment]
Not quite. If you read on you'll see that lists experimental support, you have to run Node with `--experimental-modules` and even in Node 18+ it's experimental: https://nodejs.org/api/esm.html

If you insist on allowing `import` only, you should use the `.mjs` file extension, and run with `--experimental-modules`, but keep in mind that this is not a default in any cloud setting like GCP or AWS where people are very likely wanting to minify code; also you get only default exports, you might want to update your usage docs.

I wonder why you wouldn't want to support something as fundamental as `require`.

**Comment by coderaiser** [comment]
Are you willing for a PR to build a commonjs version on publish with help of https://esbuild.github.io/ or https://github.com/swc-project/swc, for example? So both supported.
